force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casual</fullName>
            </value>
            <value>
                <fullName>Backcountry</fullName>
            </value>
            <value>
                <fullName>Expedition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Enthusiast</fullName>
            </value>
            <value>
                <fullName>Racer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <label>Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nylon</fullName>
            </value>
            <value>
                <fullName>Ripstop Polyester</fullName>
            </value>
            <value>
                <fullName>Synthetic Fill</fullName>
            </value>
            <value>
                <fullName>Leather &amp; Mesh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>MSRP</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestProductController.cls
@isTest
public class TestProductController {

    public static void createProducts() {
        List<Product__c> products = new List<Product__c>();

        products.add(new Product__c(
                        Name='Sample Bike 1',
                        MSRP__c=1000,
                        Category__c='Mountain',
                        Level__c='Beginner',
                        Material__c='Carbon'));

        products.add(new Product__c(
                        Name='Sample Bike 2',
                        MSRP__c=1200,
                        Category__c='Mountain',
                        Level__c='Beginner',
                        Material__c='Carbon'));

        insert products;
    }

    static testMethod void testGetProducts() {
        TestProductController.createProducts();
        String filters = '{"searchKey":"Sample", "maxPrice":2000, "categories": ["Mountain"], "levels": ["Beginner"], "materials":["Carbon"]}, 1';
        Test.startTest();
        PagedResult result = ProductController.getProducts(filters, 1);
        Test.stopTest();
        System.assertEquals(result.records.size(), 2);
    }
    static testMethod void testGetSimilarProducts() {
        TestProductController.createProducts();
        Test.startTest();
        String filters = '{"searchKey":"Sample", "maxPrice":2000, "categories": ["Mountain"], "levels": ["Beginner"], "materials":["Carbon"]}, 1';
        PagedResult result = ProductController.getProducts(filters, 1);
        Product__c productToCompare = (Product__c)result.records[0];
        Product__c[] products = ProductController.getSimilarProducts(productToCompare.Id, null);
        System.assertEquals(products.size(), 1);
    }

}