force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductRecordInfoController.cls
public with sharing class ProductRecordInfoController {

    @AuraEnabled(Cacheable=true)
    public static List<String> getRecordInfo(String productOrFamilyName) {
        List<String> recordInfo = new List<String>();

        List<Product__c> cProductList = [SELECT ID FROM Product__c WHERE NAME = :productOrFamilyName];
        if (cProductList.size() > 0) {
            recordInfo.add(cProductList[0].ID);
            recordInfo.add('Product__c');
            return recordInfo; 
        }

        List<Product_Family__c> cProductFamilyList = [SELECT ID FROM Product_Family__c WHERE NAME = :productOrFamilyName];
        if (cProductFamilyList.size() > 0) {
            recordInfo.add(cProductFamilyList[0].ID);
            recordInfo.add('Product_Family__c');
            return recordInfo; 
        }
        return null;
    }
}