force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Reseller Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseller Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Reseller Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestOrderController.cls
@isTest
public class TestOrderController {

    @testSetup
    static void setup() {
        Account acc = new Account(
            Name = 'Sample Account'
        );
        insert acc;

        Order__c newOrder = new Order__c(
            Account__c = acc.Id
        );
        insert newOrder;

        Product__c p = new Product__c(
            Name = 'Sample Product'
        );
        insert p;

        Order_Item__c orderItem = new Order_Item__c(
            Order__c = newOrder.Id,
            Product__c = p.Id
        );
        insert orderItem;

    }

    @isTest
    static void testGetOrderItems() {
        Order__c newOrder = TestOrderController.createOrder();
        Id orderId = newOrder.Id;
        TestOrderController.createOrderItem(orderId);
        Test.startTest();
        List<Order_Item__c> orderItems = OrderController.getOrderItems(orderId);
        Test.stopTest();
        System.assertEquals(orderItems.size(), 1);
    }

}